spring:
  output:
    ansi:
      enabled: always
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: yyyy-MM-dd
logging:
  level:
    '[org.springframework]': INFO
    '[com.in28minutes.springboot]': DEBUG
server:
  port: 9090
